### ISSUE TITLE
Lib does not support HEIC images

### ISSUE THREAD

**Issue by progid** [hui-z/image_gallery_saver#201] opened 2022-01-11 13:53 UTC
Can't save .heic image. No future result after calling `ImageGallerySaver.saveFile`

**Comment by tomsun** [comment] 2022-11-15 21:22
seems like that might have been addressed here: https://github.com/hui-z/image_gallery_saver/commit/6e2133a64fec11c979ae7efb6132c048b721dcb6

committed the same day as this issue was opened.

caveat: the most recent published version is 13 months old at the time of writing i.e. older than the fix

**Comment by BetterB0y** [comment] 2022-11-15 21:34
I can confirm, there is some issue with saving .heic

**Comment by tomsun** [comment] 2022-11-21 20:25
the github master works for me with .heic files.

pubspec.yaml
```
  image_gallery_saver:
    git:
      url: https://github.com/hui-z/image_gallery_saver.git
      ref: master
```

or clone to a local dir and use `path:` instead of `git:`

-----


> No future result 

@progid @BetterB0y  wheras the latest from pub.dev - i.e. 13 months old and before the patch - probably behaves just like that: if the file extension isn't recognized as an image nor a video, then it looks like nobody ever calls `result()` on the Swift side https://github.com/hui-z/image_gallery_saver/blob/6e2133a64fec11c979ae7efb6132c048b721dcb6/ios/Classes/SwiftImageGallerySaverPlugin.swift#L33-L41

**Comment by BetterB0y** [comment] 2022-12-03 11:35
@tomsun So why you do not push new version to pub.dev?

**Comment by tomsun** [comment] 2022-12-03 12:00
@BetterB0y not my project. Perhaps @zaihui is the one to ask?

**Comment by tomsun** [comment] 2022-12-03 17:29
@xqqlv and @woodwen seem to be the ones who have commited to master during the last year. Although access to the account that was used to push to pub.dev might or might not be a separate matter

**Comment by woodwen** [comment] 2023-05-31 08:39
I'm so sorry, it's updated now

**Closed by woodwen** 2023-05-31 08:39 UTC
